# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  #dockerRegistryServiceConnection: '26d49d2a-dbd7-46ce-8922-61b2030c07cd'
  #imageRepository: 'nycpivottanzudotnetcore'
  #containerRegistry: 'pivotregistry.azurecr.io'
  #dockerfilePath: '$(Build.SourcesDirectory)/src/Tanzu.Dotnet.Core.Web.Mvc/Dockerfile'
  tag: '$(Build.BuildId)'
  commit: '$(Build.SourceVersion)'
  src: '$(Build.SourcesDirectory)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    container: nycpivot/tbs-tools:latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          create-kubeconfig.sh

          secretName=harbor-secret
          export REGISTRY_PASSWORD=${HARBOR_PASS}
          
          kp secret delete harbor-secret || true
          kp secret create harbor-secret --registry ${HARBOR_SERVER} --registry-user ${HARBOR_USER}
                    
          kp image status tanzu-dotnet-core-web-mvc > /dev/null 2>&1 || image=0
         
          if [[ $image != 0 ]]; then
            kp image patch tanzu-dotnet-core-web-mvc --git https://github.com/nycpivot/tanzu-dotnet-core.git --git-revision $(commit) -w
            #kubectl replace -f $(src)/deploy.yaml --force
            kubectl set image deployment/tanzu-dotnet-core-web-mvc tanzu-dotnet-core-web-mvc=tanzu-dotnet-core-web-mvc:latest -n tanzu-advanced
          else
            kp image create tanzu-dotnet-core-web-mvc --tag demo.goharbor.io/tanzu-advanced/tanzu-dotnet-core-web-mvc --git https://github.com/nycpivot/tanzu-dotnet-core.git --git-revision $(commit) -w
            
            #kubectl create deployment --image demo.goharbor.io/tanzu-advanced/tanzu-dotnet-core-web-mvc:latest
            #kubectl apply -f $(src)/deploy.yaml
          fi

          #kubectl apply -f $(src)/deploy.yaml

          sleep 60
          kubectl get svc -n tanzu-advanced
      env:
        #TBS_CLUSTER_SERVER_ADDRESS: https://tanzu-build-service-apiserver-112658748.us-east-1.elb.amazonaws.com:6443
        #TBS_CLUSTER_CERTIFICATE_AUTHORITY_DATA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5ekNDQWJPZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01Ea3hOakUzTXpnME4xb1hEVE13TURreE5ERTNORE0wTjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3lPCkVCUCsvNFlYcWUyc3ltb3NoZVpkbnZITjBLcExhYkhyS0t2dXV4NXlDSmVPMTdOS0pNWk4zYU8vMGkrbDkrenEKZm81RzBLWWxXSWFiYmVYcVBOY0J1cHp5bUthbFRIcDhRdDFrNXpVM0V3QkcyT2puRTh5VHpKWllVc004MWZ3aQpjKzd5MUFwMkxsMkRjMWRpNno1LzFZNWo2aUhVbFl1M0czN296WTF2WVMxWWxHM0NkaEc3Mms0Rk94bUxxQ2FXCmxUVEszOW5xSERuZmZoUWVwSlQ0Z1BHR3U3S1pXcTlVOGxjR1FiT3diaUhmelBPc1QzaFZtaEllczM3OWtaamIKL2piVXZ6cklMRXNUWlkrSGNsdkY5VTBZVEExWUxqV0VsOElsQjY5SnJBUWUrMmdGb0tLcGlTKzZtVTQ2dlhZMQpQbjJNOUhFQnFsTEtrTnJCMEkwQ0F3RUFBYU1tTUNRd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSUo3S1VRRmYxK3VWdllyNTlmR3Y4ZFQKcEFFUCszeE4rcTh1N3RjSU9BaFhDWXhkamx5SmxXdmdMcThTVXpTcWFLeElDb3g3c2NUd3MyWFduRDhWelRhVwpONWdKamhsOEg3U3BEM1ZyNUQxd1dKVjk4eGVqUlkrbk9DRnJObTkvcFFPTnhHU2xUSTZlNTZ2QitzL0JCeU95Ck82bGN0TExkMWlrOGJENXYzV2RhMEt1cWV4TmZybkdlK1Q2Z0UzVkkzQ3BmcERta2RvaHJLWXVFRU5OOGtyTWoKb29ONGJUbVFCOEw4Nng3QWNzRWZrQnBISlVBS29LdVlxK2VXMUdkVFJ1TTVHcXpWaWczMnJEdGtyNGNUamdZdwo0cm5OcHNuTS9CdkxIdytqdDlmb2lqbFJFZE1jODZraHhiMlZXeXBwbzJMRHVqWGloREl2enFHRUdVK3dVSTA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        #TBS_CLUSTER_CLIENT_CERTIFICATE_DATA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJQjdsb2dDS0pHSHN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TURBNU1UWXhOek00TkRkYUZ3MHlNVEE1TVRZeE56UXpORGhhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTFzL2d0T0ZUSjlGaUVSTWQKemJlUHIzQlpPdVZEbWZHRDdTd0tqSngra0syN1lINUk3a3ZOWGpvOHZaZmRMcE44WlhMdE52M2NxcU9lNkwzLwpYK0hGWUJwNmc2QzR5SUVBeW1FYzQ1MWVRWFJxK1ZDL0lhQWpNay84ZjlMa3dPME5HVnRlOTZMTHN0WXF4N0w1Cm9VTkJmVStkMkZrSUs0NUUrcjdYMk04YkE1dnlxYWlBS241MVV2K2RSWDZSdHFDYlR6NytoM1FNWmF4UGVOZjMKQktCNmt6UFZxSzEvS3B0NUp4U0VTNXlpL01OUkFCaWtqcHZMeHZHcUZyWWVyTXllTmNEbzdlcldLMlpEZTRRMgphclJKcWVQTGxSNi8xTzVYaFRza2VXSGcyaWVsNHo4aFhab3d3K2IxNEI2d0NOd0RJSDdiM3RqWWpTTmdFR3NGCmMyVkV1UUlEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDLy8vamV3V1FsUE5jWFJLMVN6Q09xb3c2d1BNUjZEVGdabQpkaklVRTkzK2p6UTdpU3gvemNJUnZLcGlqdnlPVitmd2RZSDZNeEdFc28rUHJtc2hmd3JwS1Z3RnByeE0zWGZ1CmoxdktKVXNPSjAwb0s5MnE2U0UrcmZZZnpSSFFTcXhGNVhpSS9kcnVNOWF1WmJTNFEyTlpFSlRVR0M0bzFSTDYKK3g0aEJGZzRtcEZvT1BYdTJwRk9BY1hpVXdHbnJZeGliQWhiZlVTbHpBb1lmcnZoVUpiTHZiaFdCbE9FREsyNgplM2s2cFpiSkdHdE4xdm1qYkdNZkZkOU9vMDgvYnZWVG53cFdxSkZqKzJrRnV3VkM2ZlQzOEZoUWxKUmQzd3VWCk1YZk5TeTFlOGJrVlBGL1JyMTQ5aE4rWmpidUhWY1VGbGJZb2hWckV5N1JtRkRrUTRwVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        #TBS_CLUSTER_CLIENT_KEY_DATA: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBMXMvZ3RPRlRKOUZpRVJNZHpiZVByM0JaT3VWRG1mR0Q3U3dLakp4K2tLMjdZSDVJCjdrdk5Yam84dlpmZExwTjhaWEx0TnYzY3FxT2U2TDMvWCtIRllCcDZnNkM0eUlFQXltRWM0NTFlUVhScStWQy8KSWFBak1rLzhmOUxrd08wTkdWdGU5NkxMc3RZcXg3TDVvVU5CZlUrZDJGa0lLNDVFK3I3WDJNOGJBNXZ5cWFpQQpLbjUxVXYrZFJYNlJ0cUNiVHo3K2gzUU1aYXhQZU5mM0JLQjZrelBWcUsxL0twdDVKeFNFUzV5aS9NTlJBQmlrCmpwdkx4dkdxRnJZZXJNeWVOY0RvN2VyV0syWkRlNFEyYXJSSnFlUExsUjYvMU81WGhUc2tlV0hnMmllbDR6OGgKWFpvd3crYjE0QjZ3Q053RElIN2IzdGpZalNOZ0VHc0ZjMlZFdVFJREFRQUJBb0lCQUVMZ0Z0SFpNRjArRjJ5LwphZERvcThmdmp5Z0J4aWtBQXBWczE1L3MvSTRvT0NTVFREczd5Q1RrdHBKRDNDMHE1MWhpRGkzSG5OSlcvQnJ6ClE3VGpBZUtvZTZuTStKb2JaMWFhSXpkTmY5R2EzODdjYjVTVldUL0puUTlpWmFzV1liU2FPSmVaekJiU0RDRjkKdTYrVDA2aWloNzZhQVN3bUw1MXNtcUE1NGV3ZUoxMGxHRW9nZVBjUGNxT2hNL2M1N1JiQTdibWxGRWpBM3N0OApDQURuVitRNTNyblVMVC94cWNPYU1KMkovdkhzNEE1N3ozM3pValFCVDJFMk5CaW9Ha2R5VlBta0psTDRVM0UwClNtZDhYM1VVY0VXUXh1aGgwWVQyb2laeDBZN3kwTmYxSDZYclQzemxDUzk2cEhJKzEreW53NjMrZTlQRlFXYmYKR00zaUNpMENnWUVBL1RnSDJNU29nZDBKbUpaRlJIa25nS3psVTZhV2lIVHNjcE5MN0JmaXFWTkcwWUlOVFhnRQp2c2NJV3dVNW5TRE1MK3BZZDZ4bzlPdm5TNnpkNloyUWRIRk50V2ZpNFFzUi93ejZYSkYyVVU5VlZqa0lQNTBsClRyT2MzWnd6YUtSM1pucW5XUTFnamhxM0tWQjNIWmdHVVlmUzVmcDdEdWM5MVpaaVZ4MEwvdE1DZ1lFQTJTdmMKQ01MV29KNGVqS2cvNU9GQXNDQVBhRVZTQjRNZmMvS1pLVEI2dElKeEFDTzZoR0hKTyt2aTUwU0ZyQTlpeS9rVgpBYy9vTzFxNkJrQWVMZEpRNUZNTnM2NUVyN0JQK0pQVkFEdXoyZjhXd1FUbG42aTlCeTJKZGFuNkZjZXgrMWZPCklSV0hySGhmSTNnT05YZTAreXF2NVdoNU45SlRQUnYySSszKzdzTUNnWUFRM0laSlBPOHJscGhvL0xpb0VwazYKekVpSkJYTElxMkNEVUtPaG1RV1MyT1RDVnJLa0VmWGU3a24wSmFqc2VaNmZJaSs1NkZVazJnQ1EzWFg1ZEhDRwpFSFZvT3Y2MGxaUWhNN0FJTWZkNitwbG9JR3dZTUZLbnB2WXZHNU9neURMYk5CZW9xbWRmancvYlJHeHFJQkZyCnBHdTZ2Szh0RXVEZk5DQmdSS0xqMlFLQmdCV2h5TWtXbjBwZ2RhcU5GOUEwbjd6cmRKMXVTajExVWl5NmZZY2MKelJ3dDRoT2hlM0swU3RjdEoremhabTg5R1JvNE5WOTQxaWtUWUhRKzdzS2hzRzBOMk0rTkRFcHp4WU45TmpwUAp1QnAremtWcnQzT3YyeVJiNU5WVG1SV1NUcWc2bHMyMDEwN1dycU5aMGhDQlhBV291dHlmQzNRRC8wYVhBbTJSCngxTUJBb0dBS0pObVZZeXZkQjJlVlBDSWYwZTBPNWd2RnE4Y0FMeGlYQndsa0Zqb3p2bllCa2ZET1VxUUprMVMKTWphYkhpSXJ5ZlQ1UWtNeTZVZlFiWU1uOGV3dEd3ak1KRGdkNk94N2ZFL3laVk8wcjIySnpZV2lmd2JkTU9xRQpHaWJFR2VDK1dpd1JXakJySWxxT3NmVy94ZHE1c0NlNm15ZEIxdW4vaWRxY09GOXN3TjQ9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
        #HARBOR_SERVER: demo.goharbor.io
        #HARBOR_USER: mjames
        HARBOR_PASS: GenesisC#1V.1


