apiVersion: apps/v1
kind: Deployment
metadata:
	name: tanzu-dotnet-core-web-mvc
	labels:
		app: tanzu-dotnet-core-web-mvc
spec:
	replicas: 1
	selector:
		matchLabels:
			app: tanzu-dotnet-core-web-mvc
	template:
		metadata:
			labels:
				app: tanzu-dotnet-core-web-mvc
		spec:
			containers:
			-	name: tanzu-dotnet-core-web-mvc
				image: tanzuregistry.azurecr.io/tanzu-dotnet-core-web-mvc
				ports:
					containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
	name: tanzu-dotnet-core-web-mvc
	labels:
		app: tanzu-dotnet-core-web-mvc
spec:
	ports:
	-	name: http-port
		port: 80
		targetPort: 80
	selector:
		app: tanzu-dotnet-core-web-mvc
	type: LoadBalancer